name: Publish package to GitHub Packages
on:
  push:
    branches:
      - 'main'
jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file

      - name: npm install
        run: npm install

      - name: Prepare package
        run: npm run prepare

      - name: npm publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
